# Site settings
title: Android Kotlin Guides
email: your-email@domain.com
description: >
  This is the official page for the Android Testing Support Library, a library provided by Google for testing Android apps.
baseurl: "/kotlin-guides"
url: "https://android.github.io"

# Build settings
markdown: kramdown

collections:
  - changes

gems:
  - octopress-autoprefixer
  - jekyll-redirect-from

exclude:
  - vendor
